### ISSUE TITLE
Feature request: safe delay status time after reboot für Interactive delay switch

### ISSUE THREAD

**Issue by Nastras** [hans-1/homebridge-cmdtriggerswitch#2]
After trying out some things with your plugin, I noticed that when I activate the Interactive Delay switch "stateful": true, the slider on the switch disappears.

Would it be possible to add a function when the switch is on to save the remaining delay time so that the delay time is continued after a restart of the Homebridge instance or the pi?

I am not sure if it is possible so I would like to hear your opinion?

Thanks a lot!

Regards
Nastras

**Comment by hans-1** [comment]
(A) Stateful switches (stateful: true) don't have a delay time, this is by design. Therefor they also have no interactive delay (and no slider). If you turn them on, they  stay on forever until you turn them off. The state (on or off) is persisted, i.e. if Homebridge reboots the previous state is maintained. 

(B) Stateless switches (stateful: false) are automatically turned off after the specified delay time and they also support the interactive delay (with the slider). The delay value is persisted, i.e. if Homebridge reboots the interactively defined delay value is maintained but neither the on/off state nor the remaining delay-time to turn the switch off.

If I got you right, you suggest for (B) that after a reboot of Homebridge, a stateless switch checks if there is a remaining delay-time and stays on this time. I think, this is a useful feature and I'll implement it with Release 1.2.

**Comment by Nastras** [comment]
Thank you very much for the explanation.

> If I got you right, you suggest for (B) that after a reboot of Homebridge, a stateless switch checks if there is a remaining delay-time and stays on this time. I think, this is a useful feature and I'll implement it with Release 1.2.

That's what I meant, I'm glad you're implementing it 👍👍👍

Thanks a again!

**Comment by Nastras** [comment]
@hans-1 Thank you for the update 🙏👍🙏

Small question still, do you intend to support more device types with your plugin in the future or will it stay with switches?

I personally would be very happy if you would expand your plugin sometime. If no I am still happy about the plugin 😉

**Comment by hans-1** [comment]
At the moment I do not plan to support other device types. To be honest, it very much depends on my personal needs ;-)

**Comment by Nastras** [comment]
It's a pity, I would have liked to have several types of devices with your interactive delay function 😉

But understandable.
